const GLOSSARY = [
    // ===== 1. General Security Concepts =====
    { term: "CIA Triad", reading: "シーアイエー トライアド", category: "基本概念", definition: "情報セキュリティの3大要素。機密性（Confidentiality）、完全性（Integrity）、可用性（Availability）の頭文字。すべてのセキュリティ対策はこの3つを守ることを目的とする。" },
    { term: "Confidentiality", reading: "機密性", category: "基本概念", definition: "許可された者だけが情報にアクセスできること。暗号化やアクセス制御で実現する。" },
    { term: "Integrity", reading: "完全性", category: "基本概念", definition: "情報が不正に改ざんされていないこと。ハッシュやデジタル署名で検証する。" },
    { term: "Availability", reading: "可用性", category: "基本概念", definition: "必要なときに情報やシステムにアクセスできること。冗長化やバックアップで実現する。" },
    { term: "Non-repudiation", reading: "否認防止", category: "基本概念", definition: "送信者が後からその行為を否定できないようにすること。デジタル署名で実現する。" },
    { term: "AAA", reading: "トリプルエー", category: "基本概念", definition: "Authentication（認証）、Authorization（認可）、Accounting（アカウンティング）の略。アクセス管理の3つの基本プロセス。" },
    { term: "Authentication", reading: "認証", category: "基本概念", definition: "ユーザーやデバイスの身元を確認するプロセス。パスワード、生体認証、証明書などで行う。" },
    { term: "Authorization", reading: "認可", category: "基本概念", definition: "認証後に、そのユーザーがどのリソースにアクセスできるかを決定するプロセス。" },
    { term: "Accounting", reading: "アカウンティング", category: "基本概念", definition: "誰が・いつ・何をしたかを記録・追跡すること。ログ管理や監査証跡で実現する。" },
    { term: "Zero Trust", reading: "ゼロトラスト", category: "基本概念", definition: "「決して信頼せず、常に検証する」というセキュリティモデル。ネットワーク内外を問わず、すべてのアクセスを検証する。" },
    { term: "Defense in Depth", reading: "多層防御", category: "基本概念", definition: "複数のセキュリティ層を重ねて防御する戦略。1つの層が突破されても、次の層で防御できる。" },
    { term: "Least Privilege", reading: "最小権限の原則", category: "基本概念", definition: "ユーザーやプロセスに対して、業務に必要な最小限のアクセス権限のみを付与する原則。" },
    { term: "Separation of Duties", reading: "職務分離", category: "基本概念", definition: "重要な業務を複数人で分担し、一人に権限が集中しないようにする原則。不正行為を防止する。" },
    { term: "Need to Know", reading: "知る必要性", category: "基本概念", definition: "業務上知る必要がある情報のみにアクセスを制限する原則。最小権限と関連する。" },
    { term: "Due Diligence", reading: "デューデリジェンス", category: "基本概念", definition: "リスクを事前に調査・分析すること。セキュリティ対策を計画する段階で行う。" },
    { term: "Due Care", reading: "デューケア", category: "基本概念", definition: "調査結果に基づいて、合理的なセキュリティ対策を実施すること。Due Diligenceの次のステップ。" },
    { term: "Gap Analysis", reading: "ギャップ分析", category: "基本概念", definition: "現在のセキュリティ状態と目標とするセキュリティ状態の差異を分析すること。" },

    // ===== 2. Cryptography =====
    { term: "Encryption", reading: "暗号化", category: "暗号技術", definition: "平文を暗号文に変換すること。データの機密性を保護する基本技術。" },
    { term: "Symmetric Encryption", reading: "共通鍵暗号", category: "暗号技術", definition: "暗号化と復号に同じ鍵を使う方式。AES、DES、3DESなどが代表例。高速だが鍵配布が課題。" },
    { term: "Asymmetric Encryption", reading: "公開鍵暗号", category: "暗号技術", definition: "公開鍵と秘密鍵のペアを使う方式。RSA、ECC、DHなどが代表例。鍵配布が容易だが処理速度が遅い。" },
    { term: "AES", reading: "エーイーエス", category: "暗号技術", definition: "Advanced Encryption Standard。128/192/256ビット鍵の共通鍵暗号。現在の標準的な暗号アルゴリズム。" },
    { term: "RSA", reading: "アールエスエー", category: "暗号技術", definition: "素因数分解の困難さに基づく公開鍵暗号。暗号化とデジタル署名の両方に使用。最低2048ビット推奨。" },
    { term: "ECC", reading: "イーシーシー", category: "暗号技術", definition: "Elliptic Curve Cryptography（楕円曲線暗号）。RSAより短い鍵長で同等の強度を実現。モバイルやIoTで有用。" },
    { term: "Hashing", reading: "ハッシュ", category: "暗号技術", definition: "任意のデータから固定長の値を生成する一方向関数。SHA-256、SHA-3が推奨。MD5やSHA-1は非推奨。" },
    { term: "SHA-256", reading: "エスエイチエー256", category: "暗号技術", definition: "Secure Hash Algorithm。256ビットのハッシュ値を生成。現在広く使われている安全なハッシュアルゴリズム。" },
    { term: "Digital Signature", reading: "デジタル署名", category: "暗号技術", definition: "送信者の秘密鍵で署名し、公開鍵で検証する仕組み。完全性・認証・否認防止を提供。" },
    { term: "PKI", reading: "ピーケーアイ", category: "暗号技術", definition: "Public Key Infrastructure（公開鍵基盤）。証明書の発行・管理・失効を行う仕組み。CA、RA、CRLなどで構成。" },
    { term: "Certificate Authority (CA)", reading: "認証局", category: "暗号技術", definition: "デジタル証明書を発行・管理する信頼された第三者機関。証明書の正当性を保証する。" },
    { term: "CRL", reading: "シーアールエル", category: "暗号技術", definition: "Certificate Revocation List（証明書失効リスト）。無効化された証明書のリスト。定期的に公開される。" },
    { term: "OCSP", reading: "オーシーエスピー", category: "暗号技術", definition: "Online Certificate Status Protocol。証明書の有効性をリアルタイムで確認するプロトコル。CRLより効率的。" },
    { term: "TLS", reading: "ティーエルエス", category: "暗号技術", definition: "Transport Layer Security。通信の暗号化プロトコル。HTTPSはTLSを使用。現在はTLS 1.2/1.3が推奨。" },
    { term: "Key Escrow", reading: "鍵エスクロー", category: "暗号技術", definition: "暗号鍵のコピーを第三者に預けること。鍵を紛失した場合の復旧に使用する。" },
    { term: "Salting", reading: "ソルト", category: "暗号技術", definition: "パスワードのハッシュ化時にランダムなデータを追加すること。レインボーテーブル攻撃を防ぐ。" },
    { term: "Key Stretching", reading: "鍵ストレッチング", category: "暗号技術", definition: "パスワードのハッシュ計算を繰り返し行い、ブルートフォース攻撃を困難にする技術。PBKDF2、bcryptなど。" },
    { term: "Steganography", reading: "ステガノグラフィ", category: "暗号技術", definition: "画像や音声ファイルなどにデータを隠す技術。暗号化とは異なり、データの存在自体を隠す。" },

    // ===== 3. Identity and Access Management =====
    { term: "MFA", reading: "多要素認証", category: "認証・アクセス管理", definition: "Multi-Factor Authentication。2つ以上の認証要素を組み合わせる方式。知識・所持・生体の3要素。" },
    { term: "TOTP", reading: "ティーオーティーピー", category: "認証・アクセス管理", definition: "Time-based One-Time Password。時刻に基づいて生成される一時的なパスワード。Google Authenticatorなどで使用。" },
    { term: "HOTP", reading: "エイチオーティーピー", category: "認証・アクセス管理", definition: "HMAC-based One-Time Password。カウンタに基づくワンタイムパスワード。TOTPの前身。" },
    { term: "SSO", reading: "シングルサインオン", category: "認証・アクセス管理", definition: "Single Sign-On。一度の認証で複数のシステムやアプリケーションにアクセスできる仕組み。" },
    { term: "SAML", reading: "サムル", category: "認証・アクセス管理", definition: "Security Assertion Markup Language。XMLベースの認証・認可データ交換標準。SSOで広く使用。" },
    { term: "OAuth", reading: "オーオース", category: "認証・アクセス管理", definition: "認可のためのオープンスタンダード。サードパーティアプリにリソースへの限定的アクセスを許可する。" },
    { term: "OpenID Connect", reading: "オープンアイディーコネクト", category: "認証・アクセス管理", definition: "OAuth 2.0上に構築された認証レイヤー。ユーザーの身元確認（認証）を提供する。" },
    { term: "LDAP", reading: "エルダップ", category: "認証・アクセス管理", definition: "Lightweight Directory Access Protocol。ディレクトリサービスにアクセスするプロトコル。Active Directoryで使用。" },
    { term: "Kerberos", reading: "ケルベロス", category: "認証・アクセス管理", definition: "チケットベースの認証プロトコル。Active Directoryのデフォルト認証方式。KDC、TGT、サービスチケットで構成。" },
    { term: "RADIUS", reading: "ラディウス", category: "認証・アクセス管理", definition: "Remote Authentication Dial-In User Service。ネットワークアクセスの認証・認可・アカウンティング（AAA）プロトコル。" },
    { term: "TACACS+", reading: "タカクスプラス", category: "認証・アクセス管理", definition: "Terminal Access Controller Access-Control System Plus。Cisco開発のAAAプロトコル。全通信を暗号化。RADIUSより細かい制御が可能。" },
    { term: "RBAC", reading: "ロールベースアクセス制御", category: "認証・アクセス管理", definition: "Role-Based Access Control。役割（ロール）に基づいてアクセス権限を割り当てる方式。管理が容易。" },
    { term: "DAC", reading: "任意アクセス制御", category: "認証・アクセス管理", definition: "Discretionary Access Control。リソースの所有者がアクセス権限を設定する方式。Windowsのファイル権限など。" },
    { term: "MAC", reading: "強制アクセス制御", category: "認証・アクセス管理", definition: "Mandatory Access Control。セキュリティラベルに基づいてシステムがアクセスを制御する方式。軍事・政府機関で使用。" },
    { term: "ABAC", reading: "属性ベースアクセス制御", category: "認証・アクセス管理", definition: "Attribute-Based Access Control。ユーザー属性、リソース属性、環境条件に基づく柔軟なアクセス制御。" },
    { term: "PAM", reading: "特権アクセス管理", category: "認証・アクセス管理", definition: "Privileged Access Management。管理者権限アカウントへのアクセスを管理・監視・制御する仕組み。" },
    { term: "Federation", reading: "フェデレーション", category: "認証・アクセス管理", definition: "異なる組織間で認証情報を共有・信頼する仕組み。SAML、OAuth、OpenID Connectで実現する。" },
    { term: "Biometrics", reading: "生体認証", category: "認証・アクセス管理", definition: "指紋、虹彩、顔認識、声紋などの身体的特徴を使った認証。「あなた自身」を確認する。" },

    // ===== 4. Threats and Attacks =====
    { term: "Phishing", reading: "フィッシング", category: "脅威・攻撃", definition: "偽のメールやWebサイトで個人情報を騙し取るソーシャルエンジニアリング攻撃。最も一般的な攻撃の一つ。" },
    { term: "Spear Phishing", reading: "スピアフィッシング", category: "脅威・攻撃", definition: "特定の個人や組織を標的にしたフィッシング攻撃。標的について事前に調査し、巧妙なメールを送る。" },
    { term: "Whaling", reading: "ホエーリング", category: "脅威・攻撃", definition: "経営幹部（CEO、CFOなど）を標的にしたスピアフィッシング。高い権限や決裁権を悪用する。" },
    { term: "Vishing", reading: "ヴィッシング", category: "脅威・攻撃", definition: "Voice Phishing。電話を使ったフィッシング攻撃。銀行やIT部門を装って情報を聞き出す。" },
    { term: "Smishing", reading: "スミッシング", category: "脅威・攻撃", definition: "SMS Phishing。SMSテキストメッセージを使ったフィッシング攻撃。" },
    { term: "Social Engineering", reading: "ソーシャルエンジニアリング", category: "脅威・攻撃", definition: "人間の心理的弱点を突いて情報やアクセスを不正に取得する手法。技術的攻撃ではなく人的攻撃。" },
    { term: "Pretexting", reading: "プリテキスティング", category: "脅威・攻撃", definition: "偽の身分や口実で相手を騙す手法。IT管理者や上司になりすまして情報を聞き出す。" },
    { term: "Tailgating", reading: "テールゲーティング", category: "脅威・攻撃", definition: "正規の入室者の後について、認証なしで制限区域に入る物理的な侵入手法。ピギーバッキングとも。" },
    { term: "Shoulder Surfing", reading: "ショルダーサーフィン", category: "脅威・攻撃", definition: "他人の肩越しに画面やキーボード入力を覗き見る攻撃。パスワードやPINの盗み見。" },
    { term: "Dumpster Diving", reading: "ダンプスターダイビング", category: "脅威・攻撃", definition: "ゴミ箱から機密情報を拾い集める攻撃。書類のシュレッダー処理が対策。" },
    { term: "Ransomware", reading: "ランサムウェア", category: "脅威・攻撃", definition: "データを暗号化して身代金を要求するマルウェア。バックアップが最も重要な対策。" },
    { term: "Trojan", reading: "トロイの木馬", category: "脅威・攻撃", definition: "有用なソフトウェアに見せかけた悪意のあるプログラム。自己複製はしないが、バックドアを作成する場合がある。" },
    { term: "Worm", reading: "ワーム", category: "脅威・攻撃", definition: "ネットワークを通じて自己複製・拡散するマルウェア。ユーザーの操作なしで感染が広がる。" },
    { term: "Rootkit", reading: "ルートキット", category: "脅威・攻撃", definition: "OSの深い部分に潜伏し、自身の存在を隠すマルウェア。検出が非常に困難。" },
    { term: "Keylogger", reading: "キーロガー", category: "脅威・攻撃", definition: "キーボード入力を記録するソフトウェアまたはハードウェア。パスワードやクレジットカード番号を窃取。" },
    { term: "RAT", reading: "ラット", category: "脅威・攻撃", definition: "Remote Access Trojan。攻撃者がリモートからシステムを完全に制御できるマルウェア。" },
    { term: "Logic Bomb", reading: "ロジックボム", category: "脅威・攻撃", definition: "特定の条件が満たされたときに悪意のあるコードを実行するマルウェア。日付や特定のイベントがトリガー。" },
    { term: "SQL Injection", reading: "SQLインジェクション", category: "脅威・攻撃", definition: "Webアプリケーションの入力フィールドにSQL文を挿入してデータベースを不正操作する攻撃。入力値の検証とパラメータ化クエリで防御。" },
    { term: "XSS", reading: "クロスサイトスクリプティング", category: "脅威・攻撃", definition: "Cross-Site Scripting。Webページに悪意のあるスクリプトを挿入する攻撃。Stored、Reflected、DOMの3種類。" },
    { term: "CSRF", reading: "シーエスアールエフ", category: "脅威・攻撃", definition: "Cross-Site Request Forgery。ユーザーの認証済みセッションを利用して不正なリクエストを送信する攻撃。" },
    { term: "Buffer Overflow", reading: "バッファオーバーフロー", category: "脅威・攻撃", definition: "プログラムのバッファ領域を超えるデータを送り込み、任意のコードを実行する攻撃。" },
    { term: "DDoS", reading: "ディードス", category: "脅威・攻撃", definition: "Distributed Denial of Service。複数の攻撃元からサービスに大量のトラフィックを送り、利用不能にする攻撃。" },
    { term: "Man-in-the-Middle (MitM)", reading: "中間者攻撃", category: "脅威・攻撃", definition: "通信の間に割り込み、データを盗聴・改ざんする攻撃。TLS/SSL証明書の検証で防御。On-path attackとも呼ばれる。" },
    { term: "Replay Attack", reading: "リプレイ攻撃", category: "脅威・攻撃", definition: "正規の認証データを傍受・再送信して不正アクセスする攻撃。タイムスタンプやナンスで防御。" },
    { term: "DNS Poisoning", reading: "DNSポイズニング", category: "脅威・攻撃", definition: "DNSキャッシュに偽の情報を注入し、ユーザーを偽サイトに誘導する攻撃。" },
    { term: "ARP Spoofing", reading: "ARPスプーフィング", category: "脅威・攻撃", definition: "偽のARPメッセージを送信して、攻撃者のMACアドレスを正規のIPアドレスに関連付ける攻撃。" },
    { term: "Brute Force", reading: "ブルートフォース", category: "脅威・攻撃", definition: "総当たり攻撃。すべての組み合わせを試してパスワードを解読する。アカウントロックアウトで防御。" },
    { term: "Dictionary Attack", reading: "辞書攻撃", category: "脅威・攻撃", definition: "辞書に載っている単語やよく使われるパスワードのリストを使って解読を試みる攻撃。" },
    { term: "Rainbow Table", reading: "レインボーテーブル", category: "脅威・攻撃", definition: "事前計算されたハッシュ値とパスワードの対応表。ソルト付きハッシュで防御。" },
    { term: "Pass the Hash", reading: "パスザハッシュ", category: "脅威・攻撃", definition: "パスワードのハッシュ値を直接使って認証を突破する攻撃。パスワード自体を知る必要がない。" },
    { term: "Privilege Escalation", reading: "権限昇格", category: "脅威・攻撃", definition: "低い権限のアカウントから管理者権限を不正に取得すること。水平的と垂直的の2種類がある。" },
    { term: "Zero-Day", reading: "ゼロデイ", category: "脅威・攻撃", definition: "パッチや対策が存在しない未知の脆弱性、またはそれを悪用する攻撃。発見日から「0日」のため。" },
    { term: "APT", reading: "エーピーティー", category: "脅威・攻撃", definition: "Advanced Persistent Threat（高度な持続的脅威）。国家支援のハッカー集団による長期的で高度な攻撃。" },
    { term: "Supply Chain Attack", reading: "サプライチェーン攻撃", category: "脅威・攻撃", definition: "ソフトウェアやハードウェアの供給過程に悪意のあるコードを仕込む攻撃。SolarWinds事件が代表例。" },
    { term: "Insider Threat", reading: "内部脅威", category: "脅威・攻撃", definition: "組織内部の人物（従業員、契約者）による脅威。意図的な不正行為と過失によるものがある。" },
    { term: "Typosquatting", reading: "タイポスクワッティング", category: "脅威・攻撃", definition: "有名なドメイン名のタイプミスを利用した偽サイト。例：gogle.com → google.com。" },
    { term: "Watering Hole", reading: "水飲み場攻撃", category: "脅威・攻撃", definition: "標的がよく訪問するWebサイトにマルウェアを仕込む攻撃。特定のグループを狙う。" },
    { term: "Cryptojacking", reading: "クリプトジャッキング", category: "脅威・攻撃", definition: "他人のコンピュータリソースを無断で使用して暗号通貨をマイニングする攻撃。" },

    // ===== 5. Network Security =====
    { term: "Firewall", reading: "ファイアウォール", category: "ネットワーク", definition: "ネットワークトラフィックをルールに基づいて許可・拒否するセキュリティ装置。パケットフィルタリング、ステートフル、NGFWなど。" },
    { term: "NGFW", reading: "次世代ファイアウォール", category: "ネットワーク", definition: "Next-Generation Firewall。従来のファイアウォール機能に加え、アプリケーション識別、IPS、マルウェア検知を統合。" },
    { term: "IDS", reading: "侵入検知システム", category: "ネットワーク", definition: "Intrusion Detection System。ネットワークやシステムへの侵入を検知して管理者に通知する。ブロックはしない。" },
    { term: "IPS", reading: "侵入防止システム", category: "ネットワーク", definition: "Intrusion Prevention System。侵入をリアルタイムで検知・ブロックする。IDSの機能に加えて積極的に防御する。" },
    { term: "VPN", reading: "ブイピーエヌ", category: "ネットワーク", definition: "Virtual Private Network。暗号化されたトンネルを作り、安全にリモートアクセスする技術。IPsec、SSL/TLSベースなど。" },
    { term: "IPsec", reading: "アイピーセック", category: "ネットワーク", definition: "IP Security。ネットワーク層で通信を暗号化・認証するプロトコルスイート。AH（認証）とESP（暗号化+認証）で構成。" },
    { term: "DMZ", reading: "ディーエムゼット", category: "ネットワーク", definition: "Demilitarized Zone（非武装地帯）。内部ネットワークとインターネットの間に配置される緩衝ゾーン。公開サーバーを配置。" },
    { term: "NAC", reading: "ナック", category: "ネットワーク", definition: "Network Access Control。ネットワークに接続するデバイスのセキュリティ状態を確認し、アクセスを制御する仕組み。" },
    { term: "VLAN", reading: "ブイラン", category: "ネットワーク", definition: "Virtual LAN。物理的なネットワーク構成に関係なく、論理的にネットワークを分離する技術。セグメンテーションに使用。" },
    { term: "SDN", reading: "エスディーエヌ", category: "ネットワーク", definition: "Software-Defined Networking。ネットワークの制御をソフトウェアで集中管理する技術。柔軟な構成変更が可能。" },
    { term: "WAF", reading: "ワフ", category: "ネットワーク", definition: "Web Application Firewall。Webアプリケーションへの攻撃（SQLi、XSSなど）を検知・ブロックするファイアウォール。" },
    { term: "Proxy Server", reading: "プロキシサーバー", category: "ネットワーク", definition: "クライアントとサーバーの間に位置し、通信を中継する。フォワードプロキシとリバースプロキシがある。" },
    { term: "SIEM", reading: "シーム", category: "ネットワーク", definition: "Security Information and Event Management。セキュリティログを集約・相関分析し、脅威を検出するシステム。" },
    { term: "SOAR", reading: "ソアー", category: "ネットワーク", definition: "Security Orchestration, Automation, and Response。セキュリティ運用の自動化・効率化ツール。SIEMと連携して使用。" },
    { term: "Port Scanning", reading: "ポートスキャン", category: "ネットワーク", definition: "対象ホストの開いているポートを調査する手法。Nmapが代表的なツール。攻撃の偵察段階で使用。" },
    { term: "Network Segmentation", reading: "ネットワーク分離", category: "ネットワーク", definition: "ネットワークを小さなセグメントに分割してセキュリティを向上させる。攻撃の横展開を防止する。" },
    { term: "802.1X", reading: "ハチマルニテンイチエックス", category: "ネットワーク", definition: "ポートベースのネットワークアクセス制御標準。有線・無線LANの認証に使用。RADIUS/EAPと連携。" },
    { term: "DNS over HTTPS (DoH)", reading: "ディーエヌエスオーバーエイチティーティーピーエス", category: "ネットワーク", definition: "DNS問い合わせをHTTPS経由で暗号化して行うプロトコル。DNSトラフィックの盗聴を防止。" },

    // ===== 6. Security Architecture =====
    { term: "Cloud Security", reading: "クラウドセキュリティ", category: "セキュリティ設計", definition: "クラウド環境におけるセキュリティ対策。責任共有モデルに基づいてプロバイダーとユーザーが分担。" },
    { term: "IaaS", reading: "アイアース", category: "セキュリティ設計", definition: "Infrastructure as a Service。仮想サーバーやネットワークを提供。ユーザーはOS以上を管理。AWS EC2など。" },
    { term: "PaaS", reading: "パース", category: "セキュリティ設計", definition: "Platform as a Service。アプリケーション実行環境を提供。ユーザーはアプリとデータを管理。Azure App Serviceなど。" },
    { term: "SaaS", reading: "サース", category: "セキュリティ設計", definition: "Software as a Service。アプリケーション自体を提供。ユーザーはデータとアクセス管理のみ。Microsoft 365、Salesforceなど。" },
    { term: "Containerization", reading: "コンテナ化", category: "セキュリティ設計", definition: "アプリケーションとその依存関係を隔離された環境（コンテナ）にパッケージ化する技術。Dockerが代表例。" },
    { term: "Microservices", reading: "マイクロサービス", category: "セキュリティ設計", definition: "アプリケーションを小さな独立したサービスに分割するアーキテクチャ。それぞれ個別にデプロイ・スケール可能。" },
    { term: "Infrastructure as Code (IaC)", reading: "アイエーシー", category: "セキュリティ設計", definition: "インフラ構成をコードで定義・管理する手法。Terraform、Ansibleなど。一貫性と再現性を確保。" },
    { term: "CASB", reading: "キャスビー", category: "セキュリティ設計", definition: "Cloud Access Security Broker。クラウドサービスの利用状況を可視化し、セキュリティポリシーを適用するツール。" },
    { term: "Honeypot", reading: "ハニーポット", category: "セキュリティ設計", definition: "攻撃者を誘引するためのおとりシステム。攻撃手法の分析や早期検知に使用。" },
    { term: "Honeynet", reading: "ハニーネット", category: "セキュリティ設計", definition: "複数のハニーポットで構成されるネットワーク。より現実的な環境で攻撃者の行動を観察する。" },
    { term: "Load Balancer", reading: "ロードバランサー", category: "セキュリティ設計", definition: "トラフィックを複数のサーバーに分散する装置。可用性とパフォーマンスを向上させる。DDoS対策にも有効。" },
    { term: "HSM", reading: "エイチエスエム", category: "セキュリティ設計", definition: "Hardware Security Module。暗号鍵の生成・保管・管理を行う専用ハードウェア。物理的に保護された環境で鍵を管理。" },
    { term: "TPM", reading: "ティーピーエム", category: "セキュリティ設計", definition: "Trusted Platform Module。暗号鍵の保管やハードウェアの完全性検証を行うセキュリティチップ。BitLockerで使用。" },
    { term: "Secure Boot", reading: "セキュアブート", category: "セキュリティ設計", definition: "起動時にファームウェアやOSの署名を検証し、改ざんされたソフトウェアの起動を防ぐ仕組み。" },
    { term: "Embedded System", reading: "組み込みシステム", category: "セキュリティ設計", definition: "特定の機能を実行するために設計された専用コンピュータシステム。IoTデバイス、SCADA、医療機器など。" },
    { term: "SCADA", reading: "スキャダ", category: "セキュリティ設計", definition: "Supervisory Control and Data Acquisition。産業用制御システム。発電所、水道、製造業で使用。サイバー攻撃の標的になりやすい。" },

    // ===== 7. Security Operations =====
    { term: "Vulnerability Scanning", reading: "脆弱性スキャン", category: "セキュリティ運用", definition: "システムやネットワークの脆弱性を自動的に検出するスキャン。Nessus、OpenVASなどのツールを使用。" },
    { term: "Penetration Testing", reading: "ペネトレーションテスト", category: "セキュリティ運用", definition: "実際に攻撃を試みてセキュリティの弱点を発見するテスト。脆弱性スキャンより深い評価。侵入テストとも。" },
    { term: "Patch Management", reading: "パッチ管理", category: "セキュリティ運用", definition: "ソフトウェアの更新プログラムを計画的に適用するプロセス。脆弱性対策の基本。" },
    { term: "Change Management", reading: "変更管理", category: "セキュリティ運用", definition: "システムやプロセスの変更を体系的に管理するプロセス。変更による障害やセキュリティリスクを防止。" },
    { term: "Incident Response", reading: "インシデント対応", category: "セキュリティ運用", definition: "セキュリティインシデント発生時の対応プロセス。準備→検知→封じ込め→根絶→復旧→教訓の6段階。" },
    { term: "Forensics", reading: "フォレンジック", category: "セキュリティ運用", definition: "デジタル証拠の収集・保全・分析・報告を行う調査手法。法的に有効な証拠を確保する。" },
    { term: "Chain of Custody", reading: "証拠の連鎖", category: "セキュリティ運用", definition: "証拠の収集から法廷提出までの取り扱い記録。証拠の完全性を保証するために必須。" },
    { term: "Order of Volatility", reading: "揮発性の順序", category: "セキュリティ運用", definition: "証拠収集時、消えやすいデータから先に収集する順序。レジスタ→キャッシュ→メモリ→ディスク→ログ→アーカイブ。" },
    { term: "BCP", reading: "事業継続計画", category: "セキュリティ運用", definition: "Business Continuity Planning。災害や障害発生時にビジネスを継続するための計画。DRPを含む。" },
    { term: "DRP", reading: "災害復旧計画", category: "セキュリティ運用", definition: "Disaster Recovery Plan。災害発生後にITシステムを復旧するための計画。RPOとRTOを定義。" },
    { term: "RPO", reading: "目標復旧時点", category: "セキュリティ運用", definition: "Recovery Point Objective。許容できるデータ損失の最大量（時間）。バックアップ頻度を決定する基準。" },
    { term: "RTO", reading: "目標復旧時間", category: "セキュリティ運用", definition: "Recovery Time Objective。障害発生からシステム復旧までの許容時間。短いほど高コスト。" },
    { term: "MTTR", reading: "平均修復時間", category: "セキュリティ運用", definition: "Mean Time To Repair。障害発生から復旧までの平均時間。システムの可用性指標。" },
    { term: "MTBF", reading: "平均故障間隔", category: "セキュリティ運用", definition: "Mean Time Between Failures。故障と故障の間の平均稼働時間。高いほど信頼性が高い。" },
    { term: "Backup", reading: "バックアップ", category: "セキュリティ運用", definition: "データの複製を作成すること。フル、差分、増分の3種類。3-2-1ルール（3コピー、2媒体、1オフサイト）が推奨。" },
    { term: "Hot Site", reading: "ホットサイト", category: "セキュリティ運用", definition: "即座に切り替え可能な完全装備のバックアップ施設。最も高コストだが復旧が最速。" },
    { term: "Cold Site", reading: "コールドサイト", category: "セキュリティ運用", definition: "基本的な設備のみのバックアップ施設。最もコストが低いが復旧に最も時間がかかる。" },
    { term: "Warm Site", reading: "ウォームサイト", category: "セキュリティ運用", definition: "ホットサイトとコールドサイトの中間。機器はあるがデータの同期が必要。コストと復旧時間のバランス型。" },
    { term: "Tabletop Exercise", reading: "机上演習", category: "セキュリティ運用", definition: "インシデント対応やDRPを実際にシステムを動かさず、シナリオに基づいて議論・検討する演習。" },
    { term: "IoC", reading: "侵害の指標", category: "セキュリティ運用", definition: "Indicators of Compromise。攻撃を受けた証拠となるデータ。不審なIPアドレス、ハッシュ値、ドメインなど。" },

    // ===== 8. Risk Management & Governance =====
    { term: "Risk Assessment", reading: "リスク評価", category: "リスク管理", definition: "資産に対する脅威と脆弱性を特定し、リスクのレベルを評価するプロセス。定性的・定量的手法がある。" },
    { term: "Risk Mitigation", reading: "リスク軽減", category: "リスク管理", definition: "対策を実施してリスクを許容レベルまで下げること。最も一般的なリスク対応方法。" },
    { term: "Risk Acceptance", reading: "リスク受容", category: "リスク管理", definition: "リスクのコストや影響を理解した上で、対策せずにリスクを受け入れること。" },
    { term: "Risk Avoidance", reading: "リスク回避", category: "リスク管理", definition: "リスクの原因となる活動を中止すること。リスクを完全に排除する。" },
    { term: "Risk Transference", reading: "リスク移転", category: "リスク管理", definition: "リスクを第三者に移転すること。保険への加入やアウトソーシングが代表例。" },
    { term: "SLE", reading: "エスエルイー", category: "リスク管理", definition: "Single Loss Expectancy（単一損失期待値）。1回のインシデントで予想される損失額。SLE = 資産価値 × EF。" },
    { term: "ALE", reading: "エーエルイー", category: "リスク管理", definition: "Annual Loss Expectancy（年間損失期待値）。年間の予想損失額。ALE = SLE × ARO。セキュリティ投資の判断基準。" },
    { term: "ARO", reading: "エーアールオー", category: "リスク管理", definition: "Annualized Rate of Occurrence（年間発生率）。特定のインシデントが年間に発生する予想回数。" },
    { term: "GDPR", reading: "ジーディーピーアール", category: "リスク管理", definition: "General Data Protection Regulation（EU一般データ保護規則）。EU市民の個人データ保護に関する法規制。" },
    { term: "PCI DSS", reading: "ピーシーアイ ディーエスエス", category: "リスク管理", definition: "Payment Card Industry Data Security Standard。クレジットカード情報を扱う組織のセキュリティ基準。" },
    { term: "HIPAA", reading: "ヒパー", category: "リスク管理", definition: "Health Insurance Portability and Accountability Act。米国の医療情報のプライバシーとセキュリティに関する法律。" },
    { term: "SOC 2", reading: "ソックツー", category: "リスク管理", definition: "Service Organization Control 2。サービス組織のセキュリティ、可用性、処理の完全性、機密性、プライバシーを評価する監査報告書。" },
    { term: "Data Classification", reading: "データ分類", category: "リスク管理", definition: "データを機密度に応じて分類すること。公開、社内限定、機密、極秘など。適切な保護レベルを決定する基準。" },
    { term: "Data Sovereignty", reading: "データ主権", category: "リスク管理", definition: "データが収集・保管される国の法律に従うという概念。クラウドのデータ保管場所の選択に影響。" },
    { term: "DLP", reading: "ディーエルピー", category: "リスク管理", definition: "Data Loss Prevention（データ損失防止）。機密データの不正な送信や漏洩を検知・防止するシステム。" },
    { term: "Data Masking", reading: "データマスキング", category: "リスク管理", definition: "機密データを偽のデータに置き換えて保護する技術。テスト環境でのデータ利用時に使用。" },
    { term: "Data Sanitization", reading: "データサニタイゼーション", category: "リスク管理", definition: "記憶媒体からデータを完全に消去すること。上書き、消磁（デガウス）、物理的破壊の3手法。" },
    { term: "Privacy Impact Assessment", reading: "プライバシー影響評価", category: "リスク管理", definition: "新しいシステムやプロセスが個人情報に与える影響を事前に評価するプロセス。GDPRで義務化。" },

    // ===== 9. Wireless & Mobile Security =====
    { term: "WPA3", reading: "ダブリューピーエースリー", category: "無線・モバイル", definition: "Wi-Fi Protected Access 3。最新の無線LANセキュリティ規格。SAE（Simultaneous Authentication of Equals）を使用。" },
    { term: "WPA2", reading: "ダブリューピーエーツー", category: "無線・モバイル", definition: "Wi-Fi Protected Access 2。AES-CCMPを使用する無線LANセキュリティ規格。WPA3の前世代。" },
    { term: "EAP", reading: "イーエーピー", category: "無線・モバイル", definition: "Extensible Authentication Protocol。無線LAN認証のフレームワーク。EAP-TLS、PEAP、EAP-FASTなどの方式がある。" },
    { term: "Evil Twin", reading: "悪魔の双子", category: "無線・モバイル", definition: "正規のアクセスポイントを模倣した偽のアクセスポイント。接続したユーザーの通信を傍受する。" },
    { term: "Rogue Access Point", reading: "不正アクセスポイント", category: "無線・モバイル", definition: "許可なくネットワークに接続された無線アクセスポイント。内部ネットワークへの不正アクセス経路となる。" },
    { term: "MDM", reading: "エムディーエム", category: "無線・モバイル", definition: "Mobile Device Management。組織のモバイルデバイスを一元管理するソリューション。リモートワイプ、暗号化強制などが可能。" },
    { term: "BYOD", reading: "ビーワイオーディー", category: "無線・モバイル", definition: "Bring Your Own Device。従業員が個人所有のデバイスを業務に使用すること。セキュリティポリシーの適用が課題。" },
    { term: "Geofencing", reading: "ジオフェンシング", category: "無線・モバイル", definition: "GPSやRFIDを使って仮想的な地理的境界を設定し、デバイスの動作を制御する技術。" },
    { term: "Remote Wipe", reading: "リモートワイプ", category: "無線・モバイル", definition: "紛失・盗難されたモバイルデバイスのデータを遠隔から消去する機能。MDMで実現。" },
    { term: "Bluetooth Attack", reading: "Bluetooth攻撃", category: "無線・モバイル", definition: "Bluetoothの脆弱性を悪用する攻撃。Bluejacking（メッセージ送信）、Bluesnarfing（データ窃取）などがある。" },

    // ===== 10. Application & Development Security =====
    { term: "SDLC", reading: "エスディーエルシー", category: "開発セキュリティ", definition: "Software Development Life Cycle（ソフトウェア開発ライフサイクル）。計画→設計→開発→テスト→デプロイ→保守の各段階。" },
    { term: "DevSecOps", reading: "デブセックオプス", category: "開発セキュリティ", definition: "DevOpsにセキュリティを統合したアプローチ。開発ライフサイクルの全段階でセキュリティを組み込む。" },
    { term: "SAST", reading: "サスト", category: "開発セキュリティ", definition: "Static Application Security Testing（静的解析）。ソースコードを実行せずに脆弱性を検出するテスト。" },
    { term: "DAST", reading: "ダスト", category: "開発セキュリティ", definition: "Dynamic Application Security Testing（動的解析）。実行中のアプリケーションに対して外部から脆弱性を検出するテスト。" },
    { term: "Code Review", reading: "コードレビュー", category: "開発セキュリティ", definition: "開発者が書いたコードを他の開発者がチェックするプロセス。セキュリティ上の問題を早期に発見する。" },
    { term: "Input Validation", reading: "入力値検証", category: "開発セキュリティ", definition: "ユーザーからの入力データが期待する形式であることを確認するプロセス。SQLi、XSSなどの攻撃を防ぐ基本対策。" },
    { term: "OWASP", reading: "オワスプ", category: "開発セキュリティ", definition: "Open Web Application Security Project。Webアプリケーションセキュリティのオープンコミュニティ。OWASP Top 10が有名。" },
    { term: "API Security", reading: "エーピーアイセキュリティ", category: "開発セキュリティ", definition: "APIのセキュリティ対策。認証・認可、レート制限、入力検証、暗号化通信などを含む。" },
    { term: "Sandboxing", reading: "サンドボックス", category: "開発セキュリティ", definition: "プログラムを隔離された環境で実行する技術。マルウェア解析や未知のアプリケーションのテストに使用。" },
    { term: "Fuzzing", reading: "ファジング", category: "開発セキュリティ", definition: "ランダムなデータや異常なデータを入力してソフトウェアの脆弱性やバグを発見するテスト手法。" },

    // ===== 11. Physical Security =====
    { term: "Mantrap", reading: "マントラップ", category: "物理セキュリティ", definition: "2つのドアで構成された小部屋。一方のドアが開いているときは他方が開かない。テールゲーティングを防止。アクセス制御前室とも。" },
    { term: "Bollard", reading: "ボラード", category: "物理セキュリティ", definition: "車両の侵入を防ぐ頑丈な柱。建物やデータセンター周辺に設置する物理的バリア。" },
    { term: "CCTV", reading: "シーシーティーブイ", category: "物理セキュリティ", definition: "Closed-Circuit Television。監視カメラシステム。物理的セキュリティの抑止力と証拠収集に使用。" },
    { term: "Faraday Cage", reading: "ファラデーケージ", category: "物理セキュリティ", definition: "電磁波を遮断する囲い。電磁波による盗聴（TEMPEST攻撃）やEMPからの保護に使用。" },
    { term: "Environmental Controls", reading: "環境制御", category: "物理セキュリティ", definition: "温度・湿度管理、消火設備、UPSなど、物理的な環境を適切に保つための対策。データセンターで重要。" },

    // ===== 12. Automation & Emerging Technology =====
    { term: "AI/ML in Security", reading: "AIセキュリティ", category: "新技術", definition: "人工知能と機械学習をセキュリティに応用。異常検知、マルウェア分析、脅威予測に使用。誤検知のリスクもある。" },
    { term: "Blockchain", reading: "ブロックチェーン", category: "新技術", definition: "分散型台帳技術。暗号通貨、サプライチェーン管理、改ざん防止の記録管理に使用。" },
    { term: "Quantum Computing", reading: "量子コンピューティング", category: "新技術", definition: "量子力学を利用した計算技術。現在の暗号を破る可能性があるため、ポスト量子暗号の研究が進む。" },
    { term: "Post-Quantum Cryptography", reading: "ポスト量子暗号", category: "新技術", definition: "量子コンピュータでも破れない暗号アルゴリズムの研究分野。格子ベース暗号などが候補。" },
    { term: "SASE", reading: "サシー", category: "新技術", definition: "Secure Access Service Edge。ネットワーク機能（SD-WAN）とセキュリティ機能（SWG、CASB、FWaaS）をクラウドで統合。" },
    { term: "XDR", reading: "エックスディーアール", category: "新技術", definition: "Extended Detection and Response。エンドポイント、ネットワーク、クラウドなど複数のデータソースを統合して脅威を検出・対応する。" },
    { term: "EDR", reading: "イーディーアール", category: "新技術", definition: "Endpoint Detection and Response。エンドポイントでの脅威検出・調査・対応を行うセキュリティソリューション。" },
    { term: "Threat Intelligence", reading: "脅威インテリジェンス", category: "新技術", definition: "サイバー脅威に関する情報を収集・分析し、防御に活用すること。STIX/TAXIIが標準フォーマット。" },
    { term: "MITRE ATT&CK", reading: "マイターアタック", category: "新技術", definition: "攻撃者の戦術・技術・手順（TTP）をまとめたナレッジベース。脅威の分類と防御策の策定に使用。" }
];
